# Kanagawa Alacritty Theme (TOML)

[colors.primary]
background = "#1F1F28"
foreground = "#DCD7BA"

[colors.normal]
black   = "#090618"
red     = "#C34043"
green   = "#76946A"
yellow  = "#C0A36E"
blue    = "#7E9CD8"
magenta = "#957FB8"
cyan    = "#6A9589"
white   = "#C8C093"

[colors.bright]
black   = "#727169"
red     = "#E82424"
green   = "#98BB6C"
yellow  = "#E6C384"
blue    = "#7FB4CA"
magenta = "#938AA9"
cyan    = "#7AA89F"
white   = "#DCD7BA"

[colors.cursor]
text   = "#1F1F28"
cursor = "#C8C093"

[colors.selection]
text = "#C8C093"
background = "#2D4F67"

[colors.search.matches]
foreground = "#C8C093"
background = "#2D4F67"

[colors.search.focused_match]
foreground = "#C8C093"
background = "#7E9CD8"

[colors.hints.start]
foreground = "#1F1F28"
background = "#E6C384"

[colors.hints.end]
foreground = "#E6C384"
background = "#1F1F28"

[colors.footer_bar]
background = "#2A2A37"
foreground = "#DCD7BA"
